[package]
name = "practice09_progressbar"
version = "0.1.0"
authors = ["matsu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { git = "https://github.com/mitsuhiko/indicatif.git", branch = "main" }
